pipeline {
  agent any
 
  stages {
    stage('Test') {
      steps {
        sh './gradlew test'
      }
    }

    stage('Build') {
      steps {
        sh './gradlew build'
      }
    }

    stage('Build Container') {
      steps {
        sh "docker build -t stock-service:0.0.${currentBuild.number} ."
      }
    }

    stage('Deploy Container') {
      steps {
        sh "docker stop stock-service || echo 'No stock-service container to stop'"
        sh "docker rm stock-service || echo 'No stock-service container to remove'"
        sh "docker run --name stock-service --restart unless-stopped -d --net mongo-net -e DB_HOST=mongo stock-service:0.0.${currentBuild.number}"
      }
    }
  }
}
