pipeline {
  agent any
 
  stages {
    stage('Test') {
      steps {
        sh './gradlew test'
      }
    }

    stage('Build') {
      steps {
        sh './gradlew build'
      }
    }

    stage('Build Container') {
      steps {
        sh "docker build -t trade-service:0.0.${currentBuild.number} ."
      }
    }

    stage('Deploy Container') {
      steps {
        sh "docker stop trade-service || echo 'No trade-service container to stop'"
        sh "docker rm trade-service || echo 'No trade-service container to remove'"
        sh "docker run --name trade-service --restart unless-stopped -d --net mongo-net -e DB_HOST=mongo trade-service:0.0.${currentBuild.number}"
      }
    }
  }
}
