pipeline {
  agent any
 
  stages {
    stage('Test') {
      steps {
        sh './gradlew test'
      }
    }

    stage('Build') {
      steps {
        sh './gradlew build'
      }
    }

    stage('Build Container') {
      steps {
        sh "docker build -t user-service:0.0.${currentBuild.number} ."
      }
    }

    stage('Deploy Container') {
      steps {
        sh "docker stop user-service || echo 'No user-service container to stop'"
        sh "docker rm user-service || echo 'No user-service container to remove'"
        sh "docker run --name user-service --restart unless-stopped -d --net mongo-net -e DB_HOST=mongo user-service:0.0.${currentBuild.number}"
      }
    }
  }
}
